### ISSUE TITLE
项目无法构建，下载不了包

### ISSUE THREAD

**Issue by AdminQQZ** [Omooo/BlackFish#1]
![QQ截图20190829141429](https://user-images.githubusercontent.com/12959954/63915035-8d258780-ca67-11e9-8e96-a82b875bed4b.png)
无法构建

**Comment by Omooo** [comment]
这是因为这个插件还没生成呢，你可以先这样做：
1. 注释掉 project 的 build.gradle 文件中的 classpath 'top.omooo.tinypng_plugin:tinypng_plugin:1.0'
2. 注释掉 app 的 build.gradle 文件中的 以下代码：
apply plugin: 'top.omooo.tinypng_plugin'

tinyInfo {
    //资源目录
    resourceDir = [
            "app/src/main/res",
    ]
    resourcePattern = [
            "drawable[a-z-]*",
            "mipmap[a-z-]*"
    ]
    whiteList = [

    ]
    apiKey = "AInj38Kpiz4moUpTG5tiWIaXyNJYDpnY"
}
3. 重新构建即可

PS:
这个插件是用来压缩 res 下的所有 png，文档详见：https://github.com/Omooo/Android-Notes/blob/master/blogs/Android/Gradle/TinyPngPlugin.md
如果你想使用，在终端执行：./gradlew tinyTask 即可，就会在该工程的主目录下生成一个 repo 文件下，然后再将上面一二步的代码在注释回来就好了~

还有，就是该 Project 已经不在维护了。。
(逃~

**Comment by AdminQQZ** [comment]
呜呜呜，别逃




------------------ 原始邮件 ------------------
发件人: "沐小晨曦"<notifications@github.com>; 
发送时间: 2019年8月29日(星期四) 下午2:22
收件人: "Omooo/BlackFish"<BlackFish@noreply.github.com>; 
抄送: "867711323"<867711323@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Omooo/BlackFish] 项目无法构建，下载不了包 (#1)




这是因为这个插件还没生成呢，你可以先这样做：
  
注释掉 project 的 build.gradle 文件中的 classpath 'top.omooo.tinypng_plugin:tinypng_plugin:1.0'
 
注释掉 app 的 build.gradle 文件中的 以下代码：
 apply plugin: 'top.omooo.tinypng_plugin'
  
tinyInfo {
 //资源目录
 resourceDir = [
 "app/src/main/res",
 ]
 resourcePattern = [
 "drawable[a-z-]",
 "mipmap[a-z-]"
 ]
 whiteList = [
 ] apiKey = "AInj38Kpiz4moUpTG5tiWIaXyNJYDpnY"  
}
 3. 重新构建即可
 
PS:
 这个插件是用来压缩 res 下的所有 png，文档详见：https://github.com/Omooo/Android-Notes/blob/master/blogs/Android/Gradle/TinyPngPlugin.md
 如果你想使用，在终端执行：./gradlew tinyTask 即可，就会在该工程的主目录下生成一个 repo 文件下，然后再将上面一二步的代码在注释回来就好了~
 
还有，就是该 Project 已经不在维护了。。
 (逃~
